- name: Build_Node_W_1
  os: windows
  function: build
  hostname: Build_Node_W_1
  ip: 15.83.248.200
  mac: 27832784292
  version: 1.0
  username: bamboo
  password: 1177eafe586b4459f7410f9abb393e15f2
  domain: sh

- name: Build_Node_TP_1
  os: linux
  function: build
  hostname: Build_Node_TP_1
  ip: 15.83.248.200
  mac: 27832784292
  version: 1.0
  username: bamboo
  password: 1177eafe586b4459f7410f9abb393e15f2
  domain: sh 
 
- name: windows_deploy_server1
  os: windows
  function: deploy
  hostname: windows_deploy_server1
  ip: 15.83.248.251
  mac: 5666666
  version: 1.0
  username: Administrator
  password: Shanghai2010
  domain: