ftp_settings:
  server_address: '15.83.248.251'
  username: 'automation'
  password: 'Shanghai2010'
  executable_package_path: '/jenkins'
  result_file_path: '/Repository/Files/Captured'

jenkins_settings:
  server_address: 'http://15.83.248.200:8080'
  username: 'bamboo'
  token: '1177eafe586b4459f7410f9abb393e15f2'
  build_job_linux: 'Configuration\template_jenkins_build_job_linux.xml'
  build_job_windows: 'Configuration\template_jenkins_build_job_windows.xml'

qtp_settings:
  server_address: 15.83.248.251
  username: Administrator
  password: Shanghai2010
  scripts_path:
    create_filter: 'c:\ScriptsCopy\CreateFilter'
    send_command: 'c:\ScriptsCopy\SendCommand'
    send_packages: 'c:\ScriptsCopy\SendPackages'
    get_result: 'c:\ScriptsCopy\CaptureFiles'
    discover_devices: 'c:\ScriptsCopy\DiscoverDevices'
  test_data: 'test_data.xlsx'

hpdm_settings:
  repository_path: '\\15.83.248.251\ftproot'
  os_list:
    THINPRO7: HP ThinPro 7
    WES7P: WES7P-64
    WES10: Win10IoT-64
    WES7E: WES7E
  
email_settings:
  smtp_server: 'smtp1.hp.com'
  smtp_port: 25
  default_sender: tcqa.automationframework@hp.com
  report_summary: 'template_email_report_summary.html'

report_settings:
  template_folder: 'Configuration'
  template_name: 'template_report_content.html'
  static_src: 'Configuration\static'

log_settings:
  # Default log setting
  NAME: ''
  LOG_TYPE: 'default'
  LEVEL: 'debug'
  SEPARATOR: '-'
  USE_CONSOLE: True
  IF_SCREENSHOT: False
  # Start time
  # LOG_PATH = "%Y-%m-%d_%H-%M-%S"
  # LOG_PATH = "%Y-%m-%d_%H-%M"
  LOG_PATH: "%Y-%m-%d_%H"
  #TimedRotatingFileHandler
  #    WHEN:
          # S - Seconds
          # M - Minutes
          # H - Hours
          # D - Days
          # midnight - roll over at midnight
          # W{0-6} - roll over on a certain day; 0 - Monday
  # 1 hour 1 file, no count limit
  WHEN: 'H'
  INTERVAL: 1
  BACKUP_COUNT: 0

global_settings:
  LOOP_INTERVAL: 10
